language: go
matrix:
  include:
    - go: 1.4
      env: TOOLS_CMD=golang.org/x/tools/cmd

install:
 - go get ${TOOLS_CMD}/vet
 - go get github.com/golang/lint/golint

script:
 - ./test

notifications:
  email: false
